app/views/customers.py
from app.forms import CustomerDownloadForm
from app.models import User, Device, Release
from config import basedir, Config
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from flask_login import current_user, login_required, login_user, logout_user
from flask_security import verify_password
from flask_wtf import FlaskForm
import re
import os
from urllib.parse import urlsplit
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import InputRequired, Length


class LoginForm(FlaskForm):
    username = StringField("Username", [InputRequired(), Length(min=4, max=20)])
    password = PasswordField("Password", [InputRequired(), Length(min=8, max=20)])
    submit = SubmitField("Login", render_kw={"class": "btn btn-primary"})


customers = Blueprint("customers", __name__)


@customers.route("/home/")
@customers.route("/")
def home():
    return render_template("customers/home.html")


@customers.route("/customer_login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data.lower()).first()
        if user and user.is_active:
            if verify_password(form.password.data, user.password):
                login_user(user)
                flash("Logged in successfully.")
                next_page = request.args.get("next")
                if next_page == url_for("admin.index") and "administrator" in [
                    role.name for role in user.roles
                ]:
                    next_page = url_for("admin.index")
                elif next_page is None:
                    if "administrator" in [role.name for role in user.roles]:
                        next_page = url_for("admin.index")
                    else:
                        next_page = url_for("customers.profile", username=user.username)
                return redirect(next_page)
            else:
                flash("Wrong password - Try Again...")
        else:
            flash("Invalid username.")
    return render_template("customers/login.html", form=form)


@customers.route("/customer/<username>/", methods=["GET", "POST"])
@login_required
def profile(username):
    # Only administrators may access profiles of other users
    if "administrator" not in [r.name for r in current_user.roles]:
        # Return 403 error if current user is not accessing their own profile
        if current_user.username != username:
            return render_template("errors/403.html"), 403

    # Fetch from database the device associated with provided <username>
    country = None  # Initialize country to None initially
    device = Device.query.filter_by(name=username).first()
    if device:  # Check if User has an associated device
        country = device.country
        releases = sorted(
            Release.query.join(Device).filter(Device.name == str(device)).all(),
            key=lambda r: tuple(
                int(part) if part.isdigit() else part
                for part in re.findall(r"\d+|\D+", r.version)
            ),
            reverse=True,
        )
    else:
        releases = []  # If device is not available, set releases to an empty list

    form = CustomerDownloadForm(formdata=request.form)
    # Populate the choices for release versions in the form
    form.release_version.choices = [
        # (value submitted to the form, text displayed to the user)
        (release.version, release.version)
        for release in releases
    ]

    if form.validate_on_submit():
        release_version = form.release_version.data
        release = Release.query.filter_by(version=release_version).first()

        if release:
            version = release.release_path
            return redirect(url_for("customers.download_version", version=version))
        else:
            flash("Release not found.", "error")

    return render_template(
        "customers/profile.html",
        username=username,
        device=device,
        country=country,
        releases=releases,
        form=form,
    )


@customers.route("/device/<path:version>", methods=["GET", "POST"])
@login_required
def download_version(version):
    release = Release.query.filter_by(release_path=version).first()

    version = release.release_path
    path = os.path.join(basedir, Config.UPLOAD_FOLDER, version)
    return send_file(path_or_file=path, as_attachment=True)


@customers.route("/logout/", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    flash("You have been logged out.")
    return redirect(url_for("customers.login"))

app/templates/customers/home.html
{% extends 'customers/index.html' %}
{% block title %}
<title>Homepage</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='customer_styles.css') }}">
{% endblock %}
{% block content %}
    <p>
      {% if current_user.is_authenticated %}
        <h3>Welcome, {{ current_user.username.title()}}!</h3>
      {% else %}
        <h3>Welcome to Your Company!</h3>
    </p>
      <div class="customer-home">
        <h4>Please, <a href="{{ url_for('customers.login') }}">log in!</h4>
        </div>   
    {% endif %}
{% endblock %}

app/templates/customers/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta  http-equiv="X-UA-Compatible" content="IE.edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"/>
      {% block title %}
      {% endblock %}
  </head>
  <body>
    <div class="container">
      {% if "administrator" not in current_user.roles %}
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <img src="{{ url_for('static', filename='images/your_company.png') }}" alt="Your Company logo" width="5%" height="5%" style="margin-right: 10px;">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('customers.home') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('customers.login') }}">Login</a>
                </li>
                {% else %}
                <!-- Code for authenticated users -->
                {% if 'home' in request.endpoint %}
                <!-- If on home page, link to profile -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('customers.profile', username=current_user.username) }}">Profile</a>
                </li>
                {% else %}
                <!-- If on profile page, link to home -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('customers.home') }}">Home</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('customers.logout') }}">Logout</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown link
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
              </ul>
              <form class="ms-auto d-flex flex-nowrap" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
      {% endif %}
      <div class="row">
        <div class="col">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"></script>
  </body>
  {# Option: this will render the website in dark mode
  <style>
    body {
      background-color: #212121;
      color: white
    }
  </style>
  #}
</html>

app/templates/customers/login.html
{% extends 'customers/index.html' %}
{% block title %}
<title>Login</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='customer_styles.css') }}">
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}
<p>
    <h3>Login</h3>
</p>
<div class="customer-login">
  <form method="POST" action="{{ url_for('customers.login') }}">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    <div>
      <label for="username">Username:</label>
      <input id="username" name="username" required type="text" value="">
    </div>
    <div>
      <label for="password">Password:</label>
      <input id="password" name="password" required type="password" value="">
    </div>
    <button type="submit" class="btn btn-primary submit-button">Login</button>
    {% if form.errors %}
      <ul class="errors">
        {% for field, errors in form.errors.items() %}
          {% for error in errors %}
            <li>{{ field }}: {{ error }}</li>
          {% endfor %}
        {% endfor %}
      </ul>
    {% endif %}
  </form>
</div>
{% endblock %}

app/templates/customers/profile.html
{% extends 'customers/index.html' %}
{% block title %}
  <title>{{ current_user.username.title() }}</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='customer_styles.css') }}">
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}
  <p>
    {% if "administrator" in current_user.roles %}
      <h3>{{ current_user.username.title() }}'s view of customer: {{ device }}.</h3>
    {% else %}
      <h3>{{ current_user.username.title() }}'s profile.</h3>
    {% endif %}
  </p>
  <div class="customer-profile">
    {% if device or ("administrator" in current_user.roles) %}
      {% if device %}
        <p><h5>Device: </h5>{{ device }}</p>
        <p><h5>Country: </h5>{{ country }} </p>
      {% endif %}
      <h5>
        Select software version:
        <h6>
          {# Change username=current_user.username to username=username #}
          {# This allows admin to behave as customers and download any available software #}
          <form action="{{ url_for('customers.profile', username=username) }}" method="POST">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}
            <select name="release_version">
            {% for release in releases %}
              <option value="{{ release.version }}">{{ release.version }}</option>
            {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary" style="padding: 5px 10px; font-size: 12px;">Download</button>
          </form>
        </h6>
      </h5>
      {% if "administrator" in current_user.roles %}
        <a href="{{ url_for('device_admin.selected_device_name', device_name=device.name) }}">Back to the device search</a>
      {% endif %}
    {% else %}
      <p>No device associated with this user.</p>
    {% endif %}
  </div>
{% endblock %}