app/views/students.py
import os
import re

from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required, login_user, logout_user
from flask_security import verify_password
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import InputRequired, Length

from app.extensions import db
from app.forms import DownloadForm, UploadExerciseForm
from app.helpers import (
    handle_download,
    process_download_form,
    handle_course_selection,
    validate_upload_form,
    save_exercise_file,
)
from app.models import Course, Exercise, User
from config import Config, basedir


class LoginForm(FlaskForm):
    username = StringField("Username", [InputRequired(), Length(min=4, max=20)])
    password = PasswordField("Password", [InputRequired(), Length(min=8, max=20)])
    submit = SubmitField("Login", render_kw={"class": "btn btn-primary"})


students = Blueprint("students", __name__)


@students.route("/home/")
@students.route("/")
def home():
    return render_template("students/home.html")


@students.route("/student_login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.is_active:
            if verify_password(form.password.data, user.password):
                login_user(user)
                flash("Logged in successfully.")
                next_page = request.args.get("next")
                if next_page == url_for("admin.index") and "administrator" in [
                    role.name for role in user.roles
                ]:
                    next_page = url_for("admin.index")
                elif next_page is None:
                    if "administrator" in [role.name for role in user.roles]:
                        next_page = url_for("admin.index")
                    else:
                        next_page = url_for("students.profile", username=user.username)
                return redirect(next_page)
            else:
                flash("Wrong password - Try Again...")
        else:
            flash("Specified user does not exist")
    return render_template("students/login.html", form=form)


@students.route("/student/<username>/", methods=["GET", "POST"])
@login_required
def profile(username):
    # Return 403 error if current user is not accessing their own profile
    if current_user.username != username:
        return render_template("errors/403.html"), 403

    if "student" in current_user.roles:
        download_form = DownloadForm()

        # Get list of courses for the current user
        courses = current_user.courses

        # Handle file download if the form is submitted and valid
        exercises = process_download_form(download_form, courses)

        # Handle file download if the form is submitted and valid
        file_response = handle_download(download_form)

        if file_response:
            return file_response

        return render_template(
            "students/profile.html",
            username=username,
            courses=courses,
            exercises=exercises,
            download_form=download_form,
        )

    elif "teacher" in current_user.roles:
        upload_form = UploadExerciseForm()

        # Get list of courses for the current user
        courses = current_user.courses

        upload_form.courses.choices = [(course, course) for course in courses]
        selected_course = None

        # If the user selects a course...
        if upload_form.select.data and upload_form.validate_on_submit():
            selected_course = handle_course_selection(upload_form)
            return redirect(url_for("students.profile", username=current_user.username))

        if "selected_course" in session:
            selected_course = session["selected_course"]

        if upload_form.submit.data and upload_form.validate_on_submit():
            if validate_upload_form(upload_form):
                if save_exercise_file(upload_form, selected_course, upload_form.exercise.data):
                    return redirect(url_for("students.profile", username=current_user.username))

            return render_template(
                "students/profile.html",
                username=username,
                courses=courses,
                upload_form=upload_form,
            )
        else:
            return render_template(
                "students/profile.html",
                username=username,
                courses=courses,
                upload_form=upload_form,
            )


@students.route("/logout/", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    flash("You have been logged out.")
    return redirect(url_for("students.login"))

app/templates/students/home.html
{% extends 'students/index.html' %}
{% block title %}
<title>Homepage</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='student_styles.css') }}">
{% endblock %}
{% block content %}
    <p>
      {% if current_user.is_authenticated %}
        <h3>Welcome, {{ current_user.username.title()}}!</h3>
      {% else %}
        <h3>Welcome to Your Company!</h3>
    </p>
      <div class="student-home">
        <h4>Please, <a href="{{ url_for('students.login') }}">log in!</h4>
        </div>   
    {% endif %}
{% endblock %}

app/templates/students/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta  http-equiv="X-UA-Compatible" content="IE.edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"/>
      {% block title %}
      {% endblock %}
  </head>
  <body>
    <div class="container">
      {% if "administrator" not in current_user.roles %}
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <img src="{{ url_for('static', filename='images/your_company.png') }}" alt="Your Company logo" width="5%" height="5%" style="margin-right: 10px;">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('students.home') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('students.login') }}">Login</a>
                </li>
                {% else %}
                <!-- Code for authenticated users -->
                {% if 'home' in request.endpoint %}
                <!-- If on home page, link to profile -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('students.profile', username=current_user.username) }}">Profile</a>
                </li>
                {% else %}
                <!-- If on profile page, link to home -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('students.home') }}">Home</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('students.logout') }}">Logout</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown link
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
              </ul>
              <form class="ms-auto d-flex flex-nowrap" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
      {% endif %}
      <div class="row">
        <div class="col">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"></script>
  </body>
  {# Option: this will render the website in dark mode
  <style>
    body {
      background-color: #212121;
      color: white
    }
  </style>
  #}
</html>

app/templates/students/login.html
{% extends 'students/index.html' %}
{% block title %}
<title>Login</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='student_styles.css') }}">
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}
<p>
    <h3>Login</h3>
</p>
<div class="student-login">
  <form method="POST" action="{{ url_for('students.login') }}">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    <div>
      <label for="username">Username:</label>
      <input id="username" name="username" required type="text" value="">
    </div>
    <div>
      <label for="password">Password:</label>
      <input id="password" name="password" required type="password" value="">
    </div>
    <button type="submit" class="btn btn-primary submit-button">Login</button>
    {% if form.errors %}
      <ul class="errors">
        {% for field, errors in form.errors.items() %}
          {% for error in errors %}
            <li>{{ field }}: {{ error }}</li>
          {% endfor %}
        {% endfor %}
      </ul>
    {% endif %}
  </form>
</div>
{% endblock %}

app/templates/students/profile.html
{% extends 'students/index.html' %}
{% block title %}
  <title>{{ current_user.username.title() }}</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='courses_styles.css') }}">
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}
  <p>
    <h3>{{ current_user.username.title() }}'s profile.</h3>
  </p>
  <div class="student-profile">
    {% if not courses %}
      <p>No course associated with this user.</p>
    {% else %}
      {% if "student" in current_user.roles %}
        <div class="search-box">
          <h3>{{ _fsdomain('Download a file') }}</h3>
          <form method="POST" enctype="multipart/form-data">
            {{ download_form.csrf_token }} {{ download_form.hidden_tag() }}
            <div class="form-group">
              <div class="label-field">
                <label style="float: left">Course:</label>
                <span>
                  <select name="course">
                    {% for choice_value in download_form.course.choices %}
                      <option value="{{ choice_value[0] }}">{{ choice_value[1] }}</option>
                    {% endfor %}
                  </select>
                </span>
              </div>
            </div>
            {{ download_form.select }}
            <div style="margin-bottom: 30px;"></div>
            <div class="form-group">
              <div class="label-field">
                <label style="float: left">Exercise:</label>
                <span>
                  <select name="exercise">
                    {% for choice_value in download_form.exercise.choices %}
                      <option value="{{ choice_value[0] }}">{{ choice_value[1] }}</option>
                    {% endfor %}
                  </select>
                </span>
              </div>
            </div>
            {{ download_form.submit }}
          </form>
        </div>
        <div style="clear: both"></div>      
      {% endif %}
      {% if "teacher" in current_user.roles %}
        {% include 'shared/upload_form.html' %}
      {% endif %}
    {% endif %}  
  </div>
{% endblock %}